(define (domain rovers)
  (:requirements :strips :equality)
  ; (:constants)
  (:predicates
    (Target ?o)
    (Conf ?v ?q)
    (Motion ?v ?q1 ?t ?q2)
    (HFree)
    (AtConf ?v ?q)
    (AtPose ?o ?p)
    (Holding ?o)
  )

  (:action move
    :parameters (?v ?q1 ?t ?q2)
    :precondition (and (Motion ?v ?q1 ?t ?q2)
                       (AtConf ?v ?q1))
    :effect (and (AtConf ?v ?q2)
                 (not (AtConf ?v ?q1)))
  )
  (:action pick
    :parameters (?v ?q1 ?t ?q2 ?o)
    :precondition (and (Motion ?v ?q1 ?t ?q2)
                       (AtConf ?v ?q1)
                       (AtPose ?o ?q2)
                       (Target ?o)
                       (HFree))
    :effect (and (AtConf ?v ?q2)
                 (not (AtConf ?v ?q1))
                 (not (HFree))
                 (not (AtPose ?o ?q2))
                 (Holding ?o))
  )
)