(define (domain rovers)
  (:requirements :strips :equality)
  ; (:constants)
  (:predicates
    (Target ?o)
    (Conf ?v ?q)
    (Motion ?v ?q1 ?t ?q2)
    (HFree)
    (AtConf ?v ?q)
    (Holding ?o)
  )

  ;(:action move
  ;  :parameters (?v ?q1 ?t ?q2)
  ;  :precondition (and (Motion ?v ?q1 ?t ?q2)
  ;                     (AtConf ?v ?q1))
  ;  :effect (and (AtConf ?v ?q2)
  ;               (not (AtConf ?v ?q1)))
  ;)

  (:action pick
    :parameters (?v ?q ?t ?p ?o)
    :precondition (and (Motion ?v ?q ?t ?p)
                       (AtConf ?v ?q)
                       (AtConf ?o ?p)
                       (Target ?o)
                       (HFree))
    :effect (and (AtConf ?v ?p)
                 (not (AtConf ?v ?q))
                 (not (HFree))
                 (not (AtConf ?o ?p))
                 (Holding ?o)
            )
  )
  (:action place
    :parameters (?v ?q ?t ?p ?o)
    :precondition (and (Motion ?v ?q ?t ?p)
                       (AtConf ?v ?q)
                       (Holding ?o)
                       (Target ?o)
                       (Conf ?o ?p)
                    )
    :effect (and (AtConf ?v ?p)
                 (not (AtConf ?v ?q))
                 (HFree)
                 (AtConf ?o ?p)
                 (not (Holding ?o))
            )
  )
)